name: Crear APK de Mis Papeles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar archivos
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses || true

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.9'

      - name: Descomprimir proyecto
        run: |
          mkdir build-src
          unzip -q MisPapelesAndroid-completo.zip -d build-src

      - name: Compilar APK
        working-directory: build-src/MisPapelesAndroid
        run: gradle assembleDebug --no-daemon

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: MisPapeles-APK
          path: build-src/MisPapelesAndroid/app/build/outputs/apk/debug/app-debug.apk
